version: "3.8"

services:
  inventory-api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "go run applications/inventory-api/main.go"
    environment:
      HTTP_ADDRESS: :80
      GRPC_ADDRESS: inventory-db:9090
    depends_on:
      - inventory-db 
    ports:
      - 8080:80

  inventory-db:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "go run applications/inventory-db/main.go"
    environment:
      POSTGRES_ADDRESS: postgres://postgres:pwd@postgres:5432/inventory?sslmode=disable
      GRPC_ADDRESS: :9090
    depends_on:
      - postgres 

  postgres:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - ./applications/inventory-db/service/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    ports:
      # to remove. Added to debug purpose
      - 8081:5432 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 40s