// Code generated by protoc-gen-go. DO NOT EDIT.
// source: applications/inventory-db/service/grpc/routes/reservation.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReservationStatus int32

const (
	ReservationStatus_RESERVED  ReservationStatus = 0
	ReservationStatus_BACKORDER ReservationStatus = 1
	ReservationStatus_PENDING   ReservationStatus = 2
)

var ReservationStatus_name = map[int32]string{
	0: "RESERVED",
	1: "BACKORDER",
	2: "PENDING",
}

var ReservationStatus_value = map[string]int32{
	"RESERVED":  0,
	"BACKORDER": 1,
	"PENDING":   2,
}

func (x ReservationStatus) String() string {
	return proto.EnumName(ReservationStatus_name, int32(x))
}

func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7266aac40f74334b, []int{0}
}

type ReservationLine struct {
	Product              string   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity             uint32   `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationLine) Reset()         { *m = ReservationLine{} }
func (m *ReservationLine) String() string { return proto.CompactTextString(m) }
func (*ReservationLine) ProtoMessage()    {}
func (*ReservationLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_7266aac40f74334b, []int{0}
}

func (m *ReservationLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationLine.Unmarshal(m, b)
}
func (m *ReservationLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationLine.Marshal(b, m, deterministic)
}
func (m *ReservationLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationLine.Merge(m, src)
}
func (m *ReservationLine) XXX_Size() int {
	return xxx_messageInfo_ReservationLine.Size(m)
}
func (m *ReservationLine) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationLine.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationLine proto.InternalMessageInfo

func (m *ReservationLine) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *ReservationLine) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ReserveRequest struct {
	Lines                []*ReservationLine `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReserveRequest) Reset()         { *m = ReserveRequest{} }
func (m *ReserveRequest) String() string { return proto.CompactTextString(m) }
func (*ReserveRequest) ProtoMessage()    {}
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7266aac40f74334b, []int{1}
}

func (m *ReserveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveRequest.Unmarshal(m, b)
}
func (m *ReserveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveRequest.Marshal(b, m, deterministic)
}
func (m *ReserveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveRequest.Merge(m, src)
}
func (m *ReserveRequest) XXX_Size() int {
	return xxx_messageInfo_ReserveRequest.Size(m)
}
func (m *ReserveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveRequest proto.InternalMessageInfo

func (m *ReserveRequest) GetLines() []*ReservationLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

type ReserveResponse struct {
	ID                   string             `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status               ReservationStatus  `protobuf:"varint,2,opt,name=status,proto3,enum=ReservationStatus" json:"status,omitempty"`
	Lines                []*ReservationLine `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	CreatedAt            string             `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReserveResponse) Reset()         { *m = ReserveResponse{} }
func (m *ReserveResponse) String() string { return proto.CompactTextString(m) }
func (*ReserveResponse) ProtoMessage()    {}
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7266aac40f74334b, []int{2}
}

func (m *ReserveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveResponse.Unmarshal(m, b)
}
func (m *ReserveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveResponse.Marshal(b, m, deterministic)
}
func (m *ReserveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveResponse.Merge(m, src)
}
func (m *ReserveResponse) XXX_Size() int {
	return xxx_messageInfo_ReserveResponse.Size(m)
}
func (m *ReserveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveResponse proto.InternalMessageInfo

func (m *ReserveResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ReserveResponse) GetStatus() ReservationStatus {
	if m != nil {
		return m.Status
	}
	return ReservationStatus_RESERVED
}

func (m *ReserveResponse) GetLines() []*ReservationLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *ReserveResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterEnum("ReservationStatus", ReservationStatus_name, ReservationStatus_value)
	proto.RegisterType((*ReservationLine)(nil), "ReservationLine")
	proto.RegisterType((*ReserveRequest)(nil), "ReserveRequest")
	proto.RegisterType((*ReserveResponse)(nil), "ReserveResponse")
}

func init() {
	proto.RegisterFile("applications/inventory-db/service/grpc/routes/reservation.proto", fileDescriptor_7266aac40f74334b)
}

var fileDescriptor_7266aac40f74334b = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x6b, 0xf2, 0x40,
	0x10, 0xc6, 0x4d, 0xf4, 0xf5, 0xcf, 0xf8, 0xaa, 0xe9, 0x9e, 0x82, 0xf4, 0x20, 0x39, 0x14, 0x11,
	0x9a, 0x80, 0xbd, 0xf4, 0x22, 0x45, 0x9b, 0x20, 0xd2, 0x62, 0xcb, 0x0a, 0x3d, 0xf4, 0x16, 0xe3,
	0x50, 0x16, 0x64, 0x37, 0xee, 0x4e, 0x04, 0x3f, 0x47, 0xbf, 0x70, 0x31, 0x6a, 0x63, 0x2d, 0xf4,
	0x38, 0xcf, 0xcc, 0xce, 0x6f, 0x9f, 0x79, 0xe0, 0x21, 0x4e, 0xd3, 0xb5, 0x48, 0x62, 0x12, 0x4a,
	0x9a, 0x40, 0xc8, 0x2d, 0x4a, 0x52, 0x7a, 0x77, 0xbb, 0x5a, 0x06, 0x06, 0xf5, 0x56, 0x24, 0x18,
	0x7c, 0xe8, 0x34, 0x09, 0xb4, 0xca, 0x08, 0x4d, 0xa0, 0x71, 0xaf, 0xe6, 0xd3, 0x7e, 0xaa, 0x15,
	0x29, 0x6f, 0x0a, 0x1d, 0x5e, 0x88, 0xcf, 0x42, 0x22, 0x73, 0xa1, 0x96, 0x6a, 0xb5, 0xca, 0x12,
	0x72, 0xad, 0x9e, 0xd5, 0x6f, 0xf0, 0x53, 0xc9, 0xba, 0x50, 0xdf, 0x64, 0xb1, 0x24, 0x41, 0x3b,
	0xd7, 0xee, 0x59, 0xfd, 0x16, 0xff, 0xae, 0xbd, 0x7b, 0x68, 0x1f, 0x16, 0x21, 0xc7, 0x4d, 0x86,
	0x86, 0xd8, 0x0d, 0xfc, 0x5b, 0x0b, 0x89, 0xc6, 0xb5, 0x7a, 0xe5, 0x7e, 0x73, 0xe8, 0xf8, 0x17,
	0x20, 0x7e, 0x68, 0x7b, 0x9f, 0xd6, 0xe9, 0x0f, 0xc8, 0xd1, 0xa4, 0x4a, 0x1a, 0x64, 0x6d, 0xb0,
	0x67, 0xe1, 0x11, 0x6f, 0xcf, 0x42, 0x36, 0x80, 0xaa, 0xa1, 0x98, 0x32, 0x93, 0x73, 0xdb, 0x43,
	0x76, 0xbe, 0x6c, 0x91, 0x77, 0xf8, 0x71, 0xa2, 0xe0, 0x96, 0xff, 0xe4, 0xb2, 0x6b, 0x68, 0x24,
	0x1a, 0x63, 0xc2, 0xd5, 0x98, 0xdc, 0x4a, 0x8e, 0x2a, 0x84, 0xc1, 0x08, 0xae, 0x7e, 0x21, 0xd8,
	0x7f, 0xa8, 0xf3, 0x68, 0x11, 0xf1, 0xb7, 0x28, 0x74, 0x4a, 0xac, 0x05, 0x8d, 0xc9, 0xf8, 0xf1,
	0xe9, 0x85, 0x87, 0x11, 0x77, 0x2c, 0xd6, 0x84, 0xda, 0x6b, 0x34, 0x0f, 0x67, 0xf3, 0xa9, 0x63,
	0x0f, 0x47, 0xd0, 0x3c, 0x7b, 0xce, 0x7c, 0xa8, 0x1d, 0x2d, 0xb2, 0x8e, 0xff, 0xf3, 0x4e, 0x5d,
	0xc7, 0xbf, 0x70, 0xef, 0x95, 0x26, 0xd5, 0xf7, 0xca, 0x3e, 0xb7, 0x65, 0x35, 0x4f, 0xe9, 0xee,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x53, 0xef, 0xc7, 0x3d, 0xe8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReservationClient is the client API for Reservation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReservationClient interface {
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
}

type reservationClient struct {
	cc grpc.ClientConnInterface
}

func NewReservationClient(cc grpc.ClientConnInterface) ReservationClient {
	return &reservationClient{cc}
}

func (c *reservationClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, "/Reservation/Reserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReservationServer is the server API for Reservation service.
type ReservationServer interface {
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
}

// UnimplementedReservationServer can be embedded to have forward compatible implementations.
type UnimplementedReservationServer struct {
}

func (*UnimplementedReservationServer) Reserve(ctx context.Context, req *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}

func RegisterReservationServer(s *grpc.Server, srv ReservationServer) {
	s.RegisterService(&_Reservation_serviceDesc, srv)
}

func _Reservation_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Reservation/Reserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reservation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Reservation",
	HandlerType: (*ReservationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserve",
			Handler:    _Reservation_Reserve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "applications/inventory-db/service/grpc/routes/reservation.proto",
}
